
name: Auto deploy to Development

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Copy Dockerfile
        run: |
          cp docker/Dockerfile Dockerfile

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true